### ISSUE TITLE
What's the best way to unit test custom phrases?

### ISSUE THREAD

**Issue by PhantomPayne** [lacona/lacona#7]
What's the best way to unit test custom phrases?

Let's imagine I'm creating a reusable phrase like `Distance` with it looking approximately like

```
Distance =
<sequence>
  <Number />
  <choice>
    <literal text='m' />
    <literal text='mi' />
    <literal text='mile' />
  </choice>
</sequence>
```

My initial thought would be to create a list of valid and invalid inputs and loop over them to create tests.  For example (not exact code just some pseudo code)
```
var validInputs = [{input: '10 mi', output: {value: 10, unit: units.miles}]

validInputs.forEach({input,output} -> {
   it(`parses ${input} correctly`, ->  distance.parse(input).result.is.equal.to(output));
})
```
In this case since there are multiple possible matches (mi and mile) I would be need to either add all possible matches to my tests cases or filter all the outputs to make sure my input / output combo is the best match.

Adding all possible matches seems fragile since any time I add a new choice literal I'd need to update all my units tests.
Filtering all the outputs feels like I'm fighting against the system.

What's the best way to handle this?  Maybe I'm missing something or approaching it the wrong way.

**Comment by brandonhorst** [comment]
This is an issue that I struggle with myself. Lacona Output is designed primarily to describe an *interface*, not necessarily raw data... so testing it is not always natural.

For https://github.com/lacona/lacona-phrase-datetime, assume that for each "complete" input, there is one "correct" output. That is, if the user has entered a full phrase, there should be no ambiguity there. Because I make that assumption, I just

1. Filter out all of the outputs that have `placeholder` words in them, because these are not complete.
2. Verify that there is only one output
3. Compare the raw text of the output to make sure that it is the same as the input, using 

```js
function text (input) {
  return _.map(input.words, 'text').join('')
}
```

4. Compare result value

Of course, this has some issues. It doesn't work to test what lacona outputs *as* the user is typing. And it doesn't work for cases like yours, where a valid input "10 mi" could be the initial substring of another valid input "10 mile".

In your case, I would actually modify your phrase and add a `limit` to your `<choice>`, maybe something like this.

```xml
<sequence>
  <Number />
  <literal text=' ' />
  <choice>
    <choice limit={1}>
      <literal text='m' />
      <literal text='meters' />
    </choice>
    <choice limit={1}>
      <literal text='mi' />
      <literal text='miles' />
    </choice>
  </choice>
</sequence>
```

With this, Lacona will never "miles" for the input of "mi", because one of the choices matched already. So

```
'10 m'   suggests '10 m' and '10 mi'
'10 me'  suggests '10 meters'
'10 mi'  suggests '10 mi'
'10 mil' suggests '10 miles'
```

That's possibly a better interface for the user, because it won't be making multiple suggestions that are functionally identical. It has the side effect of making your testing easier!

**Comment by PhantomPayne** [comment]
Thanks.  That makes a lot of sense.  I'll try it out this weekend and let you know how it goes.

**Comment by brandonhorst** [comment]
Closing this for now, please let me know how your trial goes.
